export const TraerTareas='traer_tareas'
export const ErrorAction='tareas_error'
export const LoadinTareas='tareas_loading'
export const cambio_usuario_id='cambio_usuario_id'
export const cambio_titulo='cambio_titulo'
export const agregada='tarea_agregada'
export const ACTUALIZAR='tarea_actualizada'